### ISSUE TITLE
ShaderEditor example doesn't work

### ISSUE THREAD

**Issue by stonelance** [Wouterdek/NodeNetwork#1]
I tried using the ShaderEditor example and it looks like there are a couple issues.  The cube.obj and suzanne.obj files are missing.  I managed to find other copies elsewhere, and then I ran into an exception in FindVariableLocation while running:
System.ArgumentException: 'cameraPos is not a uniform variable in this shader program.'

It looks like since cameraPos is not used it is probably optimized out of the shader?

Edit: once I worked around these issues it looks like the model doesn't render.  I commented out the code at the end of LoadMesh that is deleting the mesh data, and that seemed to work (RenderDoc was showing no buffers were bound).

**Comment by Wouterdek** [comment]
I fixed the issue with the missing obj files in 681efcc.
cameraPos is not used by the vertex shader, but it is passed to the fragment shader so it shouldn't be optimized away. After the obj file fix, it works fine for me.

Please let me know if you are still having issues.

**Comment by Wouterdek** [comment]
Commit dd7ec07 should fix the issues. Feel free to comment if you are still getting errors.

**Comment by stonelance** [comment]
Ok thanks.  I got latest and the exceptions appear to be fixed, but I'm still not seeing any model render.
