### ISSUE TITLE
Issue removing the last connection

### ISSUE THREAD

**Issue by MMJM** [Wouterdek/NodeNetwork#10]
Hi,

There appears to be an issue around removing connections. 

I created the example below with the Code Gen example. When you remove the last connection from "Button Events" I think the connection count is going to 0 but there is still 1 value left so the output still shows the last connection.

![image](https://user-images.githubusercontent.com/16725454/42797990-40235f30-89d5-11e8-89bb-0312c63fcf93.png)

**Comment by ccgould** [comment]
I had to break the connection to the button events completely and reconnect to update the output.

**Comment by Wouterdek** [comment]
Before the end of this week, hopefully

**Comment by ccgould** [comment]
@Wouterdek Great thanks a lot.

**Comment by Wouterdek** [comment]
The latest commit should fix this bug.
