### ISSUE TITLE
Tag property on NodeViewModel

### ISSUE THREAD

**Issue by Kiwifranky** [Wouterdek/NodeNetwork#101]
Hi,

thank you for this really great tool! I would like to ask if it is possible to ad a Tag property of type object to the NodeViewModel.
It would make it easier - hopefully not only for me - to attach additional information to a NodeViewModel.

Thanks again...

**Comment by Wouterdek** [comment]
Hi, the recommended way to add data to nodes is to [create custom node types](https://wouterdek.me/NodeNetwork/cookbook/custom_nodes).

If you want a node type with a tag, you could create something like this:

```csharp
public class TaggedNode : NodeViewModel
{
    static TaggedNode ()
    {
        Splat.Locator.CurrentMutable.Register(() => new NodeView(), typeof(IViewFor<TaggedNode>));
    }

    public object Tag { get; set; }
}

```

**Comment by Kiwifranky** [comment]
Thanks for the hint! 

I tried to inherit but because I forgot to register with Splat it was not working as expected.

Silly mistake....
