### ISSUE TITLE
No defintion for Add on Node view model

### ISSUE THREAD

**Issue by Sabuto** [Wouterdek/NodeNetwork#102]
Hi,

I am really sorry if this i snot a bug and just my stupidity but i get this error whenever i try and add a node, input or output.

Error	CS1061	'ISourceList<NodeOutputViewModel>' does not contain a definition for 'Add' and no accessible extension method 'Add' accepting a first argument of type 'ISourceList<NodeOutputViewModel>' could be found (are you missing a using directive or an assembly reference?)

and here is my code 
```
var network = new NetworkViewModel();

            //Create the node for the first node, set its name and add it to the network.
            var node1 = new NodeViewModel();
            node1.Name = "Node 1";
            network.Nodes.Add(node1);
```

**Comment by Wouterdek** [comment]
Try adding `using DynamicData;` at the top of your file.
