### ISSUE TITLE
Example quick start is broken?

### ISSUE THREAD

**Issue by Offline-R503B** [Wouterdek/NodeNetwork#103]
![image](https://user-images.githubusercontent.com/11785451/105608105-43e37f80-5da2-11eb-9416-a7fa6907786b.png)
Can you please enlighten me how to solve this.

Would love to use the lib.

**Comment by Wouterdek** [comment]
Can you post your code?

**Comment by Offline-R503B** [comment]
I am using the exact code provided in the example quick start. 

All I've done is made a new window for it. 

Since our project is catel based I tried both a catel window and a normal window but that doesn't make a difference.

**Comment by Wouterdek** [comment]
Following the instructions in [this](https://wouterdek.me/NodeNetwork/cookbook/new_project) and [this](https://wouterdek.me/NodeNetwork/cookbook/hello_world), I get a project that works without issue: [NNExampleApp.zip](https://github.com/Wouterdek/NodeNetwork/files/5862624/NNExampleApp.zip)

Make sure you didn't skip [step 0](https://wouterdek.me/NodeNetwork/cookbook/hello_world#step-0-register-nodenetwork-views).

**Comment by Offline-R503B** [comment]
> Following the instructions in [this](https://wouterdek.me/NodeNetwork/cookbook/new_project) and [this](https://wouterdek.me/NodeNetwork/cookbook/hello_world), I get a project that works without issue: [NNExampleApp.zip](https://github.com/Wouterdek/NodeNetwork/files/5862624/NNExampleApp.zip)
> 
> Make sure you didn't skip [step 0](https://wouterdek.me/NodeNetwork/cookbook/hello_world#step-0-register-nodenetwork-views).

Ohhh I feel so stupid now! I've been putting the RegisterSplat before  base.OnStartup(e); 
Now it works! 

Sorry for wasting your time!
