### ISSUE TITLE
The style is not applied to the elements of the NodeList

### ISSUE THREAD

**Issue by XDenizX** [Wouterdek/NodeNetwork#104]
Hello!

I noticed that the items in the NodeList cannot use my own graphical presentation style.
For example, I'm using a dark theme, but the items in this list remain white and it looks pretty unreadable.

![Screenshot_1](https://user-images.githubusercontent.com/43999804/109864108-7e7aea80-7c73-11eb-9076-62d0b1bc9462.png)

**Comment by Wouterdek** [comment]
I'll add a property for this.

**Comment by XDenizX** [comment]
Nice! Thanks for the reply and support of the library!
