### ISSUE TITLE
ListNode doesn't receive updates when create in code.

### ISSUE THREAD

**Issue by PlateMug** [Wouterdek/NodeNetwork#108]
Hi,

I'm having problems building my network in code from my stored values. I've been at this for a little while now and haven't been able to figure out what I might me doing wrong. ReactiveUI is new to me so I've been on a steep learning curve.

The problem affects my ValueListNodeInputViewModel<T> node. Although not shown in the code here I have successfully implemented my create nodes code for ValueNodeInputModel it's just when I have List inputs.

I have created a simplified test app with just 2 nodes for testing to keep things as simple as possible. This has 2 nodes (material and texture). A material can have many textures (in this example my texture only has a string for the filename but in the real code there are other properties).

Adding a texture to the material in the UI works fine. TexturesChanged gets notified and the MaterialFile.Value gets updated and produces a JSON output of the material and textures.

However when I add texture nodes to the NetworkViewModel.Nodes in code and create the connections the material node never gets notified. I've put break points on the Select(_ => Unit.Default) and .Connect.

Example project on GigHub
https://github.com/PlateMug/ExampleNodeList

Regards

**Comment by Wouterdek** [comment]
Finally had time to look into this, turns out it was a bug. I pushed a fix, which will be included in the next version. Thanks!

**Comment by PlateMug** [comment]
Thanks.

I confirm the fix solved the problem.

Regards
