### ISSUE TITLE
NNViewRegistrar Pending registrations seems unusable

### ISSUE THREAD

**Issue by WhitePhoera** [Wouterdek/NodeNetwork#110]
In source code just found that usage of pending registrations will register Tuple<Func<object>, Type>, but not Type itself.

Issue in line 55.
`_registerAction(t.Item1, t.GetType());`
must be 
`_registerAction(t.Item1, t.Item2);`

I assume usually RegisterSplat or RegisterToLocator called before any pending registration created, so issue was missed.

**Comment by Wouterdek** [comment]
Yup, that's a bug. Thanks for reporting it!
