### ISSUE TITLE
How to use NodeNetwork with the WinForm project?

### ISSUE THREAD

**Issue by luckygg** [Wouterdek/NodeNetwork#113]
Hi all.

Sorry, it is not an issue but I don't know where can I ask my question.

Is it possible to use NodeNetwork on the WinForm project? Does this only support the WPF project?

If it can use with the WinForm project, could you please provide any sample code or documentation?

Thanks for providing such a great library!

I'm waiting for your advise :)

Thank you.

**Comment by Wouterdek** [comment]
Only WPF is supported. It may be possible to host WPF elements in a WinForms app though, I'm not sure.
