### ISSUE TITLE
Hide output

### ISSUE THREAD

**Issue by cortex42** [Wouterdek/NodeNetwork#12]
Is it possible to hide some of the outputs of a node while it is "open" (i.e. not collapsed)? I found out that it is possible to hide the port of an output by using the `IsVisible` property but the output name is still displayed.

**Comment by Wouterdek** [comment]
If you set the `Visibility` property of the output viewmodel to `AlwaysHidden`, both the name and the port will be hidden.

**Comment by cortex42** [comment]
I already tried that, but nothing happened. There is a TreeView with CheckBoxes in my UI and the user should be able to hide/display outputs by unchecking/checking. The CheckBoxes bind to a bool property which, upon being changed, calls a method which finds out the corresponding output viewmodel and does: `outputViewModel.Visibility = isVisible ? EndpointVisibility.AlwaysVisible : EndpointVisibility.AlwaysHidden;`

**Comment by Wouterdek** [comment]
Seems like VisibleOutputs is not being updated correctly when EndpointVisibility changes. This should be resolved in a future update when NodeNetwork switches to using DynamicData for its observable lists.

**Comment by Wouterdek** [comment]
NodeNetwork now uses DynamicData, and the issue seems to be resolved. (on the master branch, not in release yet) Feel free to reopen if it is not.
