### ISSUE TITLE
Question on layout.

### ISSUE THREAD

**Issue by Sphinksz** [Wouterdek/NodeNetwork#15]
Importing a certain file type and creating the nodes + their connections programatically. Is there a way to auto-layout them so they aren't on top of each other upon creation based off connections?

**Comment by Sphinksz** [comment]
Word. I'll look into figuring it out. This would be a huge feature especially since I'm creating import/export functions. Export doesn't matter, but import I need the nodes to be placed neatly. :/

**Comment by spadino** [comment]
Looking forward for this. Definitely, for import users preset, i.e, it’s needed.

**Comment by Wouterdek** [comment]
Implemented in v3.1.0. See [here](https://wouterdek.github.io/NodeNetwork/cookbook/layout) for more info.

**Comment by evilC** [comment]
Props dude, that "LayoutAsync" demo looks like pure WitchCraft :)
