### ISSUE TITLE
Requires .NET 4.7 ?

### ISSUE THREAD

**Issue by evilC** [Wouterdek/NodeNetwork#16]
FYI, it seems that in VS2017, if I start a project and leave it on the default (For my system at least) of .NET 4.5.2, I get the following error when I try to add the NodeNetwork NuGet package:  

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'ReactiveUI.Events.WPF 9.1.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Dunno if this is intentional or what, but you may want to update the docs?  
If I switch to .NET 4.7.2, all is fine

**Comment by Wouterdek** [comment]
It is intentional, it is mentioned in the first cookbook chapter, but I guess it would be useful to add it to the github readme. Thanks!
