### ISSUE TITLE
ArgumentException in "Hello World" cookbook after updating NuGet packages

### ISSUE THREAD

**Issue by evilC** [Wouterdek/NodeNetwork#17]
The cookbook example [Hello world in under 30 lines](https://wouterdek.github.io/NodeNetwork/cookbook/hello_world) works fine if I just add the NodeNetwork NuGet package (3.0.8)  
However, if I update NuGet packages (There are 16 updated packages available - Reactive etc) then the app no longer runs:  
![](https://i.imgur.com/BgQUgol.png)  
Zipped SLN :  [NodeNetworkExample.zip](https://github.com/Wouterdek/NodeNetwork/files/2746052/NodeNetworkExample.zip)

**Comment by evilC** [comment]
FYI, if I update some of the packages, but not all, I can get it to run:  
![image](https://user-images.githubusercontent.com/1719428/50981916-eef2aa80-14f3-11e9-94db-2ffa52c64f0d.png)

**Comment by Wouterdek** [comment]
Yep, I recently noticed this too. For now, I suggest simply not updating ReactiveUI/Reactive.net yet. There will be an update of this library to the latest version of ReactiveUI next month.

**Comment by Wouterdek** [comment]
This should be fixed now
