### ISSUE TITLE
Nodes as MEF plugins?

### ISSUE THREAD

**Issue by evilC** [Wouterdek/NodeNetwork#18]
I was wondering if you see any potential blockers for supporting arbitrary Node types as MEF plugins.  
Editors and Port types will not need need to be extensible, just Node Views and ViewModels  

To clarify our desired use-case, we have an [input remapping application](https://github.com/snoothy/ucr) and are investigating using a library such as yours to allow the end-user to chain together nodes to achieve various remapping options.  
For example, a mockup of a remapper that takes two buttons (eg keyboard keys) as input, and one joystick axis as output may look vaguely like this ("Constant" node is simulating the button inputs):  
![](https://i.imgur.com/2cbcXaO.png)  
We would like to be able to allow the various nodes (eg `ButtonsToAxis` in this example) available to the end-user to be extensible via MEF plugins  
I would envisage having, for example, two port types (Buttons and Axes) which are hard-coded - all the node plugins could do is consume these port types. We would need no editors for the port values, as the input values are provided by manipulating the input device (Although editors may be useful for debugging)  
Ideally we would also want nodes to be able to have arbitrary GuiControls which control various settings etc (eg we may want a "Deadzone" node which applies a DeadZone to an axis, and would need a TextBox to input the percentage value for the DZ)

**Comment by Wouterdek** [comment]
While I have not used MEF before, I don't see any reason why it should not work.
One thing you might want to look out for is view location. ReactiveUI uses a library called Splat to find out which view type should be used for a certain viewmodel object. As described in the documentation, the viewmodel type registers its corresponding view type using a `Splat.Locator.CurrentMutable.Register()` call in a static constructor. ([ReactiveUI doc](https://reactiveui.net/docs/handbook/views/#view-location))

Now, in the past I've seen this system being a bit picky for how projects are structured. It shouldn't be a problem, but I would suggest trying to move a node view/viewmodel type to a separate DLL, loading it at runtime and seeing if it still works.

**Comment by Wouterdek** [comment]
I am going to close this issue, feel free to comment if there turns out to be a problem later on.
