### ISSUE TITLE
How to get node view or size of node?

### ISSUE THREAD

**Issue by Audionysos** [Wouterdek/NodeNetwork#19]
I want to layout nodes pragmatically but I can only see position on ViewModel but I can't see any option to get size of a node. How can I get node size so I can position them properly? Or how could I editor port position so that connection will not lay under node?

**Comment by Wouterdek** [comment]
There is no built-in way to access the node view size from the viewmodel. You would have to create a custom node view/viewmodel and bind the ActualSize property from the view to a new Size property in the viewmodel.

**Comment by Audionysos** [comment]
Thank You, I already created custom node using example found in other question but I'm unsure on how to use this react ui and from which element to get `ActualSize`. To layout nodes I need to know the sizes of all nodes, I don't know if there's some other way than standard WPF approach? Should I just fist place the nodes in view and then re-position them using `ActualSize` of my `UserControl` ? I've created [VSProjectReferencesViewer](https://github.com/Audionysos/VSProjectReferencesViewer) using your library and I would like to customize more things but can't figure out how. For example how to force input/output labels to be placed on the same row, or how to create custom port view, or how I could create an arrow on the connection curve. Do you plan to make any more tutorials in the future?

**Comment by Wouterdek** [comment]
> how to force input/output labels to be placed on the same row

There is a property called `EndpointsStackingOrientation` on the NodeView that might do what you want.

> Do you plan to make any more tutorials in the future?

I will have a week off next month, in which I plan to:
1. Update the library to the latest ReactiveUI version (including a breaking change to DynamicData)
2. Try implement a force-based layout algorithm
3. Update the documentation and add more tutorials.

**Comment by Wouterdek** [comment]
Version v3.1.0 has an automatic layouting system, and also now includes a Size property on the node viewmodel.
