### ISSUE TITLE
Arbitrary GUIs inside Nodes?

### ISSUE THREAD

**Issue by evilC** [Wouterdek/NodeNetwork#21]
Hi, so I have been fiddling with this awesome library for a little while now, starting to learn the ropes somewhat.  
It seems that GuiControls inside Nodes are intended to be an Input - an example being the DDL in Vec3MathNode (Add|Subtract|Multiply|Divide...), and in this scenario, you have very limited control over the placement of these inputs (ie only vertical order). Am I correct in assuming that for each input, there is one Editor view, and each editor view can only handle 1 or more values of the same data type? ie the vec3 with 3 floats is fine, but if I wanted two ints and a bool all on the same row in a Node, that would need to be part of the same Editor, and thus not possible.  
From my experience with a similar setup in our existing project, we find this dynamic extremely limiting - it would be really nice to have a "Body" area for a Node that contains an arbitrary view.  
I am fine with anything that has an Input or Output port visible staying with the usual stacked approach, but am I missing something, or is there no "Body" of a Node?  
To give you some insight to the kinds of use-cases I am talking about, consider this plugin from our existing app (The controls on the left are all I am talking about):  
![](https://i.imgur.com/qTR94h6.png)  
Unfortunately, in this system, we don't have DDLs or labels, but the constraints are otherwise similar to what I see with the NodeNetwork Toolkit - all we can do for GuiControls is specify row / column.  
What we *really* want is something like this:  
![](https://i.imgur.com/Kx7hFxq.png)  
However, with the current design of the Toolkit, it seems that this kind of use-case is not really catered for? Or am I, yet again, missing something? Obviously one could throw the Toolkit out the window and roll your own, but that's maybe a bit beyond my ability level right now...  
  
  
By the way, here's a recording of what I have so far - there's no actual Input/Output manipulation going on (The nodes on the left and right edges are stand-ins for the actual Inputs & Outputs), but I have the basic functionality of our app implemented using NodeNetwork
![](https://i.imgur.com/dMycz2i.gif)  
Getting something like this going has been a dream of mine for over 10 years, so from the bottom of my heart, thank you for this amazing library!

**Comment by Wouterdek** [comment]
> Am I correct in assuming that for each input, there is one Editor view, and each editor view can only handle 1 or more values of the same data type? ie the vec3 with 3 floats is fine, but if I wanted two ints and a bool all on the same row in a Node, that would need to be part of the same Editor, and thus not possible.

Yes and no. The vec3 example you give is implemented [here](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleShaderEditorApp/ViewModels/Editors/Vec3EditorViewModel.cs). It has a single value of type Vec3, but there is no reason why Vec3 could not be composed of two ints and a bool. The trick here is to create a type that holds the values, and accept an input of that type. In your editor you can then add whatever controls you want, which you can bind to any field of any type in your datatype. (See [this](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleShaderEditorApp/Views/Vec3EditorView.xaml) and [this](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleShaderEditorApp/Views/Vec3EditorView.xaml.cs)) If you don't want to do that, then you probably have to create multiple inputs. (unless you do something really custom, which I don't think seems necessary for your usecase.)

> From my experience with a similar setup in our existing project, we find this dynamic extremely limiting - it would be really nice to have a "Body" area for a Node that contains an arbitrary view.
> I am fine with anything that has an Input or Output port visible staying with the usual stacked approach, but am I missing something, or is there no "Body" of a Node?

If you want to add elements in a node that are not in an input/output, then you probably want to create a custom node view & viewmodel. I should probably create a cookbook chapter on this, but it is really similar to [this one](https://wouterdek.github.io/NodeNetwork/cookbook/custom_editor).
In your node viewmodel, you probably added a line like this:

```
static HelloWorldNode()
{
    Splat.Locator.CurrentMutable.Register(() => new NodeView(), typeof(IViewFor<HelloWorldNode>));
}
```

If you replace `new NodeView()` here with a different, custom node view type, then you can make it look however you want. A, maybe slightly limited, example can be found [here](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/ViewModels/CodeGenNodeViewModel.cs), [here](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/Views/CodeGenNodeView.xaml) and [here](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/Views/CodeGenNodeView.xaml.cs). In general, this trick can be used on pretty much all components listed [here](https://wouterdek.github.io/NodeNetwork/components) to replace their views with a custom one.

> By the way, here's a recording of what I have so far - there's no actual Input/Output manipulation going on (The nodes on the left and right edges are stand-ins for the actual Inputs & Outputs), but I have the basic functionality of our app implemented using NodeNetwork
> Getting something like this going has been a dream of mine for over 10 years, so from the bottom of my heart, thank you for this amazing library!

 Looks great so far! Its really exciting to see what usecases people find for this library. Glad you like it :)

**Comment by evilC** [comment]
Well I sort of got that far myself, but this only seems to let you add things *over* or *outside* the node - `<views:NodeView x:Name="NodeView"></views:NodeView>` *is* the whole plugin, and you do not seem to be able to add a Grid inside or anything. I would like to add something below title and the > collapser but above the first input.

**Comment by evilC** [comment]
Additionally, looking into what you said wrt vec3 etc, unless I am missing something, that would mean a custom editor with those types? (eg two ints and a bool). This would then mean that the input had to be of that type?  
To clarify, see this mockup:  
![](https://i.imgur.com/LGMfkaI.png)
What I am trying to achieve here is *n* buttons to 1 axis.  
For each button input, there is a corresponding UpDown to set the value to which to set the axis when that button is pressed. In the picture, if you press button 1, the axis will be set to 1234, if you press 2 it gets set to 5678. 
In my experiments, it seems that if I make the Editor of each input a `ButtonAndAxisPosition` class that has a `bool?` property (For the input state) plus a `short?` property (For the value to set the output to), then I cannot assign it as an editor for the `bool?` type input. If I change the type of the port to be the `ButtonAndAxisPosition` class, then I cannot connect normal `bool?` button inputs to it.  
As you can hopefully see, this does not work - I need to be able to have per-input/output options *which do not affect the port type of the input/output*

**Comment by Wouterdek** [comment]
> I would like to add something below title and the > collapser but above the first input.

Well, you can set the Template property of the NodeView to completely override its default looks. However, I guess it would be pretty convenient to have a short and easy way to add a simple control. If I add two ControlPresenters that are configurable from your custom node control, would that fit your usecase?

![765ef32f-14d0-4bfa-99f9-836406ecd9ed](https://user-images.githubusercontent.com/913101/52538537-3af37200-2d74-11e9-9d42-fee2aa975637.png)

> As you can hopefully see, this does not work - I need to be able to have per-input/output options _which do not affect the port type of the input/output_

I see 2 options here:
- You could split up the input into 2 separate inputs, one for the boolean state and one for the numerical value. This has the advantage of also allowing the numerical value to be set through a connection. (but if you don't want that, you can also hide the port for the numerical value and it will look as in your post)
- Set the port and editor type to boolean, and store the numerical value inside the editor. You can then retrieve the numerical value for an input from its corresponding editor object.

**Comment by evilC** [comment]
I am not 100% familiar with what a ControlPresenter is - will it allow arbitrary XAML?

WRT the other bit, the 2nd option sounds more preferable, I'll see if I can figure out how to do that, thanks :)

**Comment by Wouterdek** [comment]
> I am not 100% familiar with what a ControlPresenter is - will it allow arbitrary XAML?

Yes

**Comment by Wouterdek** [comment]
Version v3.1.0 now includes the `LeadingControlPresenterStyle` and `TrailingControlPresenterStyle` properties on NodeView. Look [here](https://wouterdek.github.io/NodeNetwork/cookbook/custom_node_visuals#nodeview-properties) for more information.

**Comment by evilC** [comment]
Awesome! I didn't expect anything that quick, thanks! Will have a play when I get home.

**Comment by evilC** [comment]
I managed to have a quick play while at work, I got the XAML to inject OK, could add the Example 1+2 header/footer to my node, but I have not yet worked out how to bind contained controls to my ViewModel.  

```
    <views:NodeView x:Name="NodeView">
        <views:NodeView.LeadingControlPresenterStyle>
            <Style TargetType="ContentPresenter">
                <Setter Property="ContentTemplate">
                    <Setter.Value>
                        <DataTemplate>
                            <StackPanel Orientation="Horizontal">
                                <Label Content="Deadzone %"></Label>
                                <TextBox MinWidth="50" x:Name="DeadzonePercent"></TextBox>
                            </StackPanel>
                        </DataTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
        </views:NodeView.LeadingControlPresenterStyle>
    </views:NodeView>
```

However, the namespace does not seem to contain `DeadzonePercent`.  
I tried:  
`this.Bind(ViewModel, vm => vm.Dz, v => v.DeadzonePercent.Text).DisposeWith(d);`  
`this.Bind(ViewModel, vm => vm.Dz, v => v.NodeView.DeadzonePercent.Text).DisposeWith(d);`  
etc...

Any ideas as to what I am doing wrong?

**Comment by Wouterdek** [comment]
The thing here is that the inner control you are writing is not really a control, but a template for the control. The template is then instantiated in the node view. Because it is a template it is slightly more tricky to do binding. For simpler cases you might be able to get away with doing something like is explained [here](http://taswar.zeytinsoft.com/wpf-datatemplate-bind-property-parent-viewmodel/). 

A more robust solution would be something like this:

```
<views:NodeView x:Name="NodeView">
    <views:NodeView.LeadingControlPresenterStyle>
        <Style TargetType="ContentPresenter">
            <Setter Property="Content" Value="{Binding }"></Setter> <!-- Set Content to the DataContext of the node, which is the NodeViewModel -->
            <Setter Property="ContentTemplate">
                <Setter.Value>
                    <DataTemplate>
                        <local:LeadingControlExampleView ViewModel="{Binding }"/> <!-- Create the view and set its viewmodel to the DataContext, which is the NodeViewModel -->
                    </DataTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </views:NodeView.LeadingControlPresenterStyle>
</views:NodeView>
```

```
<UserControl x:Class="ExampleCodeGenApp.Views.LeadingControlExampleView"
    ...
    >
    <Grid>
        <CheckBox x:Name="checkBoxTest" Content="Test" HorizontalAlignment="Left" VerticalAlignment="Top"/>
    </Grid>
</UserControl>
```

```
public partial class LeadingControlExampleView : IViewFor<CodeGenNodeViewModel>
{
	#region ViewModel
	public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel),
		typeof(CodeGenNodeViewModel), typeof(LeadingControlExampleView), new PropertyMetadata(null));

	public CodeGenNodeViewModel ViewModel
	{
		get => (CodeGenNodeViewModel)GetValue(ViewModelProperty);
		set => SetValue(ViewModelProperty, value);
	}

	object IViewFor.ViewModel
	{
		get => ViewModel;
		set => ViewModel = (CodeGenNodeViewModel)value;
	}
	#endregion

	public LeadingControlExampleView()
	{
		InitializeComponent();

		this.Bind(ViewModel, vm => vm.TestValue, v => v.checkBoxTest.IsChecked);
	}
}
```
Note that while I'm creating a new separate view, I'm reusing the node viewmodel. You could also create a separate viewmodel for the inner element of course.

**Comment by evilC** [comment]
OK, I finally managed to get your code sample working, and it seems like a pretty decent solution - many thanks for that!  
Is there any chance you could give inputs/outputs the same treatment? I'm not sure before makes much sense, but after would be handy.

**Comment by evilC** [comment]
For now, I used the Editor node trick you mentioned - the Editors are of the type of the port, but I do not even wire them up, I just wire up the other controls. A little hacky, but it works OK.  
That trick plus the Leaders you added enabled me to get the results I desired:  
![](https://i.imgur.com/srvReTt.gif)
![](https://i.imgur.com/m4sS4PP.gif)
