### ISSUE TITLE
Question about use of MarkupExtension in Name property

### ISSUE THREAD

**Issue by reflectronic** [Wouterdek/NodeNetwork#22]
I'm in the process of porting this project to SDK-style projects so it can multi-target .NET Framework 4.7 and .NET Core 3.0. However, some code is giving me trouble; [some XAML objects have their name set to an `{x:Static}` `MarkupExtension` pointed to a constant string.](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Themes/PortView.xaml#L20) I have done quite a bit of testing, but I invariably get this error:
> error MC3079: MarkupExtensions are not allowed for Uid or Name property values, so '{x:Static views:ConnectionView.HighlightVisualStatesGroup}' is not valid.

If anybody could help give any insight as to what's going on, that would be greatly appreciated. Thank you.

**Comment by Wouterdek** [comment]
Honestly, I'm not sure. Might have something to do with it being a template instead of a UserControl and therefore being evaluated at runtime maybe.

**Comment by reflectronic** [comment]
I did some investigation and found that this seems to be a bug with .NET Core. I've filed an issue with the WPF guys (https://github.com/dotnet/wpf/issues/378); in the meantime, while this issue is easy to work around by copy and pasting the name everywhere, I don't want to uglify the codebase like that 😄

**Comment by Wouterdek** [comment]
Since this seems to be a .NET core regression and not a NodeNetwork problem, I'll be closing this issue now.
