### ISSUE TITLE
Event to detect selecting a node

### ISSUE THREAD

**Issue by BigEpidemic** [Wouterdek/NodeNetwork#23]
I want to integrate a property grid into my program and need to detect when a user selects a node so I can display the properties I expose. How would I proceed?

**Comment by Wouterdek** [comment]
`NetworkViewModel` has a property called `SelectedNodes` which is a `IReactiveDerivedList` and contains the nodes which are currently selected. See the [ReactiveUI documentation](https://reactiveui.net/docs/handbook/obsolete/collections/reactive-list) for information on how to observe events from this list.
