### ISSUE TITLE
[Request] Categories / descriptions for node list

### ISSUE THREAD

**Issue by evilC** [Wouterdek/NodeNetwork#25]
My list of nodes is getting pretty long - is there (or are there any plans for) any built-in functionality for organizing the node list?  
It might also be nice to allow a short description of what each node does - in the list view it could be an extra line, in the tile view it could be a tooltip

**Comment by Wouterdek** [comment]
I might add some support for categories through the WPF GroupStyle/CollectionViewSource system at some point, but it will be limited as lists are not the focus of this library.

You can always create your own list control though, that gives you full control. The one included in the library isn't terribly complicated. If you use the same drag and drop operation as in NodeListView.xaml.cs, it should work fine.

**Comment by Wouterdek** [comment]
Added in commit 9e290ea.
`NodeListView` now exposes a `CVS` property which is a CollectionViewSource and can be used to set categories in the list by adding something like this:

    nodeList.CVS.GroupDescriptions.Add(new PropertyGroupDescription("YourSortingPropertyGoesHere"));

**Comment by evilC** [comment]
Only just noticed the notification for this, thanks! Will try and give it a whirl this week and feed back
