### ISSUE TITLE
Exception starting ExampleCodeGen App

### ISSUE THREAD

**Issue by SadE54** [Wouterdek/NodeNetwork#29]
Hi,

I can compile the project but I get this error when starting it : 
https://ibb.co/mD6FMny
It seems sys is looking for  "System.ValueTuple, Version=4.0.3.0"
Last V4.5 is installed . The ValueTuple dll exists in the debug folder.

I'm really stucked at this point :)

**Comment by Wouterdek** [comment]
Try enabling "Auto-generate binding redirects" under the NodeNetwork, NodeNetworkToolkit and ExampleCodeGenApp project settings. Then, clean the solution and rebuild. Does that resolve the issue?

**Comment by SadE54** [comment]
I installed NodeNetwork/Toolit from Nuget.
The 'auto generate bindings' was already set and  4.7.2 framework used but it did not help.
