### ISSUE TITLE
Replace Deprecated ReactiveLists with Dynamic Data

### ISSUE THREAD

**Issue by Col45** [Wouterdek/NodeNetwork#30]
I am in the process of updating the ReactiveUI and Reactive nuget packages to the lastest versions. I am also starting to replace all instances of `[Deprecated]ReactiveList<T>` with [Dynamic Data's](https://github.com/RolandPheasant/DynamicData) `SourceList<T>`, per the suggestion [here](https://reactiveui.net/docs/handbook/collections/) on the ReactiveUI site.

I was wondering if updating was planned or purposefully avoided. Is the use of ReactiveLists just legacy or is there a functional reason for using them that you found?

**Comment by Wouterdek** [comment]
I was waiting for [PR 218](https://github.com/RolandPheasant/DynamicData/pull/218), which has now been merged but not yet released.

**Comment by Wouterdek** [comment]
Quick status update: PR 218 has been merged, but while working on an update I found a bug in DynamicData for which I opened [issue 220](https://github.com/RolandPheasant/DynamicData/issues/220)

**Comment by Wouterdek** [comment]
Version 4.0.0 uses DynamicData
