### ISSUE TITLE
Naming Nodes

### ISSUE THREAD

**Issue by SadE54** [Wouterdek/NodeNetwork#31]
Hi,

For a FBP graph embedded system , I need to name some Nodes (not all) . So the name could be used for the embedded system to allow value editing.
For example on a graph , I have a Timer node linked to a Time integer value. I want to name the Integer value, 'Motor Time On' , so I could present a GUI on my system to edit 'Motor Time On' value. Is it possible to do this at this time ?

And thanks for your great  library !

**Comment by Wouterdek** [comment]
I'm not sure I understand your question.
You can change the name of any node by setting the Name property on the NodeViewModel.
If you want to have the user change the name of a node, there is no built-in support for this.
You can either add a button using LeadingControlPresenter, or do something more custom by creating a custom node view.

**Comment by SadE54** [comment]
In fact what the name property is the name of the 'component' , the name of the type of block ans is linked to the node class. What I need is a way to name a instantiated node . If you consider the codegenap example, theres's a integer value type of node.  I would name a first placed one 'integer A' and another one 'integer B'.

**Comment by Wouterdek** [comment]
The codegenapp example uses a nodelist. When you drag a node from the list, a new node viewmodel is created of the same type and it is added to the network. The Name property is both the name of the 'component' and of the actual instantiations. If you want to change the name of the instantiations, simply change the Name property after creation of the node.

**Comment by SadE54** [comment]
Ok , then it means we have to chose between Node name (instance name) and node type (component name).

Here's a picture from Soletta (https://github.com/solettaproject), a tool for IoT Function Block Programming:

![fbp](https://user-images.githubusercontent.com/2878768/57224494-f04b6400-7009-11e9-8acd-d9d3d2e4a8e0.png)

You can see on some nodes 2 strings : The name of the node and the type name.
 For FBP programming editors , it could be mandatory.
I hope such a management  could be be added in your library :)

**Comment by Wouterdek** [comment]
This seems like something you could add fairly easily using the `LeadingControlPresenter` property on the node view. (See example [here](https://wouterdek.github.io/NodeNetwork/cookbook/custom_node_visuals.html#nodeview-properties))
