### ISSUE TITLE
Zooming in and out

### ISSUE THREAD

**Issue by PlatypusIV** [Wouterdek/NodeNetwork#33]
Is there a way to zoom in and out further?

Also just wanted to say, that this is a pretty amazing project.

**Comment by Wouterdek** [comment]
Zooming is done by scrolling the mousewheel.
This behaviour is defined [here](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Views/Controls/DragCanvas.cs#L159) and is currently not configurable through the API.
Do you need more control, or is the current behaviour sufficient?

**Comment by PlatypusIV** [comment]
> Zooming is done by scrolling the mousewheel.
> This behaviour is defined [here](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Views/Controls/DragCanvas.cs#L159) and is currently not configurable through the API.
> Do you need more control, or is the current behaviour sufficient?

Sorry for not being more specific earlier.
Ive got a node network with a few more nodes than I anticipated originally(over 500-1000 or so) and I basically just wondered if there was a way to zoom out way further than you can at the moment, to see more nodes at once.

**Comment by Wouterdek** [comment]
Ah I see. So there currently isn't an option to do this in the API, but it shouldn't be too hard to add one.
Then again, maybe zooming out further isn't the best solution here. Maybe it would be more user-friendly to group nodes and have multiple layers of network? Or maybe it would be more convenient to the user if a minimap was available, like how modern text editors solve this problem. ([example](https://code.visualstudio.com/assets/updates/1_10/minimap-blocks-scroll.gif))

**Comment by PlatypusIV** [comment]
@Wouterdek Both of those options sound great.
Thanks for the help. Il get to work on trying to implement them. Not sure which one yet though.

**Comment by abhilashkrishnan** [comment]
Is this functionality still available?

Any example on how can I do this?
