### ISSUE TITLE
Confused by Nodelist

### ISSUE THREAD

**Issue by juli303** [Wouterdek/NodeNetwork#37]
Hey, I'm confused by the Nodelist page in your docs. I didn't understand to which viewmodel I have to add the property and method, as well as how to bind the viewmodel property to the correct viewmodel. I'm sorry for my incompetence but could you add a small example to your explanation in the docs?
Julian

**Comment by Wouterdek** [comment]
The source code of the example applications might provide some clarification.
Take a look at the [calculator example](https://github.com/Wouterdek/NodeNetwork/tree/master/ExampleCalculatorApp), more specifically the [MainViewModel class](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCalculatorApp/ViewModels/MainViewModel.cs) and corresponding [MainWindow view class](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCalculatorApp/Views/MainWindow.xaml.cs).

Does this answer your question?
