### ISSUE TITLE
[question] The way to provide NodeOutputViewModel for ValueListNodeInputViewModel

### ISSUE THREAD

**Issue by danvervlad** [Wouterdek/NodeNetwork#38]
How could I provide output from one node to ValueListNodeInputViewModel input of another one? There is no ValueNodeOutputViewModel for the IReadOnlyReactiveList<>. If I use ValueNodeOutputViewModel<IReadOnlyReactiveList<>> the value of output will be IObservable<IReadOnlyReactiveList<>> which couldn't be connect with ValueListNodeInputViewModel input.

**Comment by Wouterdek** [comment]
So if I understand correctly, you want to have a single output that produces multiple values which should be included into the connected `ValueListNodeInputViewModel` as if it were multiple outputs?

Bad news is: this is not currently possible in the latest release version.
Good news is: it is supported in an experimental branch (grouping) and will be included in a future version. Although it won't use `IReadOnlyReactiveList` as that is deprecated, but it will use `IObservableList` from DynamicData instead.

Does this answer your question?

**Comment by danvervlad** [comment]
Yes, you understood correctly. I'll wait for the stable version with this feature. Thank you for reply!
