### ISSUE TITLE
[question] Is there any way to bring selected node on front

### ISSUE THREAD

**Issue by danvervlad** [Wouterdek/NodeNetwork#39]
Is there any way to bring selected node on front?
![image](https://user-images.githubusercontent.com/32311513/61812306-e9cfca00-ae4b-11e9-9771-8b56dbc0c1d7.png)
Currently, if you select node it will be overlapped by node which added after it.

**Comment by Wouterdek** [comment]
Huh, that actually makes a lot of sense but I haven't thought about that before. Should be pretty easy to add, I'll look into it soon.

**Comment by Wouterdek** [comment]
Implemented in commit c785882

**Comment by danvervlad** [comment]
Oh, so fast! Thank you!
