### ISSUE TITLE
 I want to always display PortView

### ISSUE THREAD

**Issue by macsyums92** [Wouterdek/NodeNetwork#4]
This is what I was looking for and it is very wonderful
However, once Node is connected, checking Collapse can not shorten Node.
By rewriting a bit, I succeeded in contracting Node while connecting Node.
Now, if you press the Collapse button, PortView will be hidden and connections will not be updated.
Is it possible to display PortView or update connection information even if Collapse is checked?

**Comment by Wouterdek** [comment]
Added in c7378f6656f70d2abc878ee97e0a907e8090c162.

The next version will have a Visibility property on endpoints that allows you to always show/always hide an endpoint.

**Comment by macsyums92** [comment]
Sorry, it seems that my writing was bad.
Certainly make it a new version, and if you set EndpointVisibility.AlwaysVisible, Port will always be displayed.
However, Editor parts are still displayed.
If you checked Collapse, you wanted to hide the Editor, make the Node smaller, and keep the Port displayed.
Normally we are keeping Node in a small state, opening Editor only when changing parameters, we are planning such usage.
But this mechanism may be hard to request.
I will devise more devises whether I can manage it even by myself.

**Comment by Wouterdek** [comment]
You can implement this by binding the visibility property of your editor view to the IsCollapsed property of the parent Node.
