### ISSUE TITLE
Sometimes ports get cut in half

### ISSUE THREAD

**Issue by KayakSnail** [Wouterdek/NodeNetwork#41]
The node port connectors sometimes get cut in half depending on the size of the node:
![image](https://user-images.githubusercontent.com/53276157/61824092-10dec980-ae55-11e9-89ad-43cc95c41d94.png)
sometimes not:
![image](https://user-images.githubusercontent.com/53276157/61824159-38ce2d00-ae55-11e9-8147-dd1361dfbe75.png)

It even occurs when connected:
![image](https://user-images.githubusercontent.com/53276157/61824222-5f8c6380-ae55-11e9-8a68-65334260ff0f.png)

**Comment by Wouterdek** [comment]
I can't seem to reproduce this. Would it be possible for you to create a minimal, reproducable example? ([info](https://stackoverflow.com/help/minimal-reproducible-example))

**Comment by KayakSnail** [comment]
I'll try. If not I could send you the project I have?

**Comment by Wouterdek** [comment]
Sure

**Comment by KayakSnail** [comment]
I've sent you the project  via proofpoint.

**Comment by Wouterdek** [comment]
How do I access that?

**Comment by KayakSnail** [comment]
Did you get the invite to your email? It would have been sent from my work email.

**Comment by Wouterdek** [comment]
Ah, found it. The mail was in the spam folder. Thanks.

**Comment by Wouterdek** [comment]
Ok so this seems to be a weird WPF bug that is caused by floating point weirdness when the height takes on certain values. I changed the margins on the port and that seems to fix it. Let me know if it isn't fixed by the next commit.

**Comment by KayakSnail** [comment]
Fix confirmed:
![image](https://user-images.githubusercontent.com/53276157/66649762-e23be800-ec26-11e9-9be0-c33279d3a967.png)
