### ISSUE TITLE
[question] What could be a reason of the long time nodes creation?

### ISSUE THREAD

**Issue by danvervlad** [Wouterdek/NodeNetwork#43]
I'm using NodeNetwork 3.1.0 nuget. In my project creating of 80 nodes takes ~10sec. But Creating 80 nodes + 107 connections takes ~1m 10 sec. 

![image](https://user-images.githubusercontent.com/32311513/62044231-10ef1880-b20b-11e9-96d0-7228426bed26.png)

The timeline profiler in Rider shows the next picture

![image](https://user-images.githubusercontent.com/32311513/62044457-a8ed0200-b20b-11e9-9c72-2390daac0387.png)

I guess the reason is events which are raised by creating of connections, but i can't figure out how to avoid that. I have subscriptions on input value changed, on input connection changed. On these events I update data inside of node. I thought that networkViewModel.SuppressChangeNotifications(); helps, but it doesn't. Also in profiler picture I can see that Graph Validator's Find Loops takes ~5 sec, I guess I can turned it off while scene is loading.

**Comment by danvervlad** [comment]
After removing Validator, It takes ~44 sec on Debug build and 26 sec on Release build

**Comment by Wouterdek** [comment]
I'll try to take a look at it this weekend

**Comment by Wouterdek** [comment]
Ok, so try this:
Wherever you create a new ValueNodeInputViewModel (or a derivative), pass the following arguments to its constructor: `ValidationAction.PushDefaultValue, ValidationAction.DontValidate`.

This will disable network validation when values propagate through the network and could drastically improve performance.

**Comment by danvervlad** [comment]
The reason was a huge chain of reactive events during graph creation. I rewrites that part of code and now it take ~10 sec on Debug build. Thank you!
