### ISSUE TITLE
Connection selection

### ISSUE THREAD

**Issue by SMaton** [Wouterdek/NodeNetwork#45]
Hi,

is there any way to actually select a connection line?

I have 2 nodes and I would like to associate some parameters with the connection line between the 2 nodes. Is this possible?

**Comment by Wouterdek** [comment]
This is not included in the library. The easiest option would be to add the controls to the editors on either side of the connection. Alternatively, if you really want to select connections and put controls near the connection, it is a bit more work but its possible. Create a subclass of the ConnectionViewModel class, create and register a custom connection view class and set the connection factory in the network to produce your custom viewmodel. You then have full control over the appearance of your connections (and so can add stuff like selection)
