### ISSUE TITLE
[question] How could I change color of node?

### ISSUE THREAD

**Issue by danvervlad** [Wouterdek/NodeNetwork#46]
I've implemented live node search in nodeview. So I need a way to mark found nodes. I try to use IsSelected flag for this,  but once you drag canvas - selection is cleared. Can I focus on node (scroll canvas to make node visible)?

I've seen that it's possible here https://github.com/Wouterdek/NodeNetwork/issues/24#issuecomment-508514536

**Comment by Wouterdek** [comment]
To do this, you should create a custom node viewmodel and view. In the viewmodel, add a reactive IsMarked boolean property. Then, in the view, bind the background color of the node to this new property. When performing a search you can then set IsMarked on each found node to set its color.

For more details: check out the node classes of the CodeGen example project:
[ViewModel](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/ViewModels/CodeGenNodeViewModel.cs)
[View codebehind](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/Views/CodeGenNodeView.xaml.cs)
[View XAML](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/Views/CodeGenNodeView.xaml)
Note that `NodeType` in the example is a non-reactive readonly property. You would need a [writable reactive property](https://reactiveui.net/docs/handbook/view-models/#read-write-properties).

**Comment by danvervlad** [comment]
Thanks! It helps
