### ISSUE TITLE
[question] After adding node back to node view - no reaction on connection

### ISSUE THREAD

**Issue by danvervlad** [Wouterdek/NodeNetwork#47]
I'm working on undo/redo operation for add/remove nodes. I notice, when I do _networkViewModel.Nodes.Remove(selectedNode) and after _networkViewModel.Nodes.Add(selectedNode) with the same instance of node, all node input editors are visible and don't hide when you attach connections to them. 

Before restoring
![image](https://user-images.githubusercontent.com/32311513/62792723-85ae3680-bad8-11e9-9820-63dee33847f1.png)

After restoring
![image](https://user-images.githubusercontent.com/32311513/62792763-9e1e5100-bad8-11e9-9342-0d2e4a691c53.png)

**Comment by Wouterdek** [comment]
I can't seem to reproduce this on the latest version. Feel free to reopen if it's not fixed for you.
