### ISSUE TITLE
Autolayout for overlapping nodes causes NaN position

### ISSUE THREAD

**Issue by Varzk-Krethalen** [Wouterdek/NodeNetwork#48]
This is a fairly specific case, but I noticed when trying to autolayout a set of newly added nodes.
When there are two or more nodes in exactly the same position, such as {0,0}, autolayout will set the positions to be {NaN,NaN}. This seems to happen to any nodes connected to the overlapping nodes as well.
This causes the nodes to be immovable.
When some of the network is overlapping, but there are other nodes connected, it does not always happen, and seems to be whether there is a majority of nodes overlapping, though I need to test that more.

**Comment by Wouterdek** [comment]
Fixed. Thank you!
