### ISSUE TITLE
Whats the best way to edit a NodeListView

### ISSUE THREAD

**Issue by Dankerprouduct** [Wouterdek/NodeNetwork#49]
I'm trying to change the look of the NodeListView but I cant find any properties for the look of the scrollbar, "Add Node" label or drop down. Whats the best way to go about editing the look of those properties?

**Comment by Wouterdek** [comment]
The most flexible way is to subclass the NodeListViewModel and register your own custom view class for it. To build your own custom view class you could copy the NodeListView class and make your own adjustments. Not the most elegant solution, but this is the only option that gives you full control. For some changes you might also be able to use Styles instead. (e.g. https://stackoverflow.com/q/7527202/915418)

**Comment by Dankerprouduct** [comment]
I'll try that out. Thank you!
