### ISSUE TITLE
Auto adjust nodes

### ISSUE THREAD

**Issue by OmidID** [Wouterdek/NodeNetwork#5]
Is there any way to adjust all node automatically? i have around 100 nodes and user must move them from the corner to see all.

**Comment by Wouterdek** [comment]
Although you can set the node positions in code, there currently is no built-in way to auto-arrange nodes. 
I have something like this planned for July/August though.

**Comment by OmidID** [comment]
Ok. I'll try to order them by `GraphAlgorithms` first then adjust them to screen.
