### ISSUE TITLE
can't find docs website github to fix docs..

### ISSUE THREAD

**Issue by jeske** [Wouterdek/NodeNetwork#50]
this project looks neat.

I was just going through the "passing values between nodes" tutorial here...

  https://wouterdek.github.io/NodeNetwork/cookbook/value_nodes

And none of the instructions work out of the box, because the names are not fully qualified and they don't explain what you have to import... I got it working, but I also want to fix the page to help others not stumble over this, and I can't find the github for the documentation website itself. 

Please make the docs website github public, and put a link on the bottom of the github docs pages to that github so we can edit and improve the docs....

And make that page use the fully qualified names in the example... (or tell people what using statements to add)
```
var node1Input = new NodeNetwork.Toolkit.ValueNode.ValueNodeInputViewModel<string>();
var node2Output = new NodeNetwork.Toolkit.ValueNode.ValueNodeOutputViewModel<string>();
node2Output.Value = System.Reactive.Linq.Observable.Return("Example String");
```

**Comment by jeske** [comment]
..and similarly, I can't get the example for "Customizing Node Visuals" to work, because it leaves out too many bits.. Where do CustomViewModel and CustomNodeViewModel come from?

**Comment by FoggyFinder** [comment]
There is a `gh-pages` branch:

https://github.com/Wouterdek/NodeNetwork/blob/gh-pages/cookbook/value_nodes.md

**Comment by Wouterdek** [comment]
The documentation is indeed available on the gh-pages branch. I've added a link to the readme to clarify this as it might indeed not have been clear. I have also added links to the API reference wherever a new class is discussed in the cookbook. Hopefully that makes it easier navigate around and find whatever you need. Finally, I have also changed the class names in "Customizing Node Visuals" for consistency with the previous chapter as these were indeed confusing.

I'm going to close this issue now, as I think the changes address the issue. Feel free to reopen or create a new issue if you feel it is not resolved.
