### ISSUE TITLE
Visual enhancements

### ISSUE THREAD

**Issue by SadE54** [Wouterdek/NodeNetwork#52]
Hi,

Searching for visual scripting tools, I found Bolt for Unity : https://ludiq.io/bolt
I really like the visual rendering.
I think there's some interesting things that could be added to node network:
- adding an icon in the header part
- use icon as name for inputs/outputs
- the ability to put an input at the the same height than an input 
- editors can be at the same height than the port itself
 Maybe it's feasible by now , but maybe it could be changed directly as  properties of the nodes ?

And Thanks again for your tool :)

**Comment by Wouterdek** [comment]
Bolt does indeed have a nice layout. It looks compact yet clear.
Adding icons to the header and inputs/outputs should be fairly easy. Having the editor on the same height as the port should also be doable. 
I'm not sure what you mean with the third item though?

**Comment by SadE54** [comment]
![bolt](https://user-images.githubusercontent.com/2878768/69868966-b4306700-12ab-11ea-9068-f70c4d3b1430.png)

You can see on the pictures that all the editors are on the same Y position than the corresponding ports. Depending of your nodes , you could get a more compact node.

**Comment by Wouterdek** [comment]
I've added support for icons and moving the editor next to the port. If no icon is set and the endpoint label is empty, the editor will move up. Check out commit 0e2d244 to see this being used in the examples.
