### ISSUE TITLE
Catch DoubleClick/ Right Click on Node

### ISSUE THREAD

**Issue by SadE54** [Wouterdek/NodeNetwork#53]
Hi,

I would like to be able to manage double click on a specific node , or right click for contextual actions with it.
Is there a mechanism that allow it ?

**Comment by Wouterdek** [comment]
If you are using custom node views/viewmodels, this is pretty easy.
In the CodeGenApp example, try adding this line [here](https://github.com/Wouterdek/NodeNetwork/blob/master/ExampleCodeGenApp/Views/CodeGenNodeView.xaml.cs#L50):
`this.NodeView.Events().MouseDoubleClick.Subscribe(_ => ViewModel.Name = "test").DisposeWith(d);`
(Note that the .Events() method is part of the ReactiveUI.Events.WPF Nuget package)
This will change the title of any node that is doubleclicked to "test".

To keep things tidy, you could add a command to the viewmodel with your event handling logic and then, in the view, use InvokeCommand on the MouseDoubleClick observable to trigger it.

**Comment by SadE54** [comment]
Thanks for the tip !
