### ISSUE TITLE
Collapse node

### ISSUE THREAD

**Issue by Harttech** [Wouterdek/NodeNetwork#54]
Dunno if that's the right place but I dunno where else to ask. What do I have to do to make a node collapsable? The arrow's there but if I click on it the node's content is still there.

View of the node:
`<UserControl x:Class="TSN.CustomNodes.RegularInstructionNodes.Views.DisplayPopupView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:TSN.CustomNodes.RegularInstructionNodes.Views"
             xmlns:views="clr-namespace:NodeNetwork.Views;assembly=NodeNetwork"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">

	<views:NodeView x:Name="NodeView" Background="MediumPurple" MinWidth="400">
		<views:NodeView.TrailingControlPresenterStyle>
			<Style TargetType="ContentPresenter">
				<Setter Property="ContentTemplate">
					<Setter.Value>
						<DataTemplate>
							<Grid DataContext="{Binding}" Loaded="Element_OnLoaded">
								<Grid.RowDefinitions>
									<RowDefinition/>
									<RowDefinition/>
								</Grid.RowDefinitions>
								<Grid.ColumnDefinitions>
									<ColumnDefinition Width="Auto"/>
									<ColumnDefinition/>
								</Grid.ColumnDefinitions>

								<Label Grid.Row="0" Grid.Column="0" VerticalAlignment="Center" HorizontalAlignment="Right">Popup:</Label>
								<Label Grid.Row="1" Grid.Column="0" VerticalAlignment="Center" HorizontalAlignment="Right">Loop:</Label>

								<ComboBox Grid.Row="0" Grid.Column="1" Margin="5" VerticalContentAlignment="Center" Padding="4" ItemsSource="{Binding Path=Popups, Mode=OneWay}" SelectedItem="{Binding Path=SelectedPopup}"/>
								<CheckBox Grid.Row="1" Grid.Column="1" VerticalAlignment="Center" Margin="5" IsChecked="{Binding Path=Loop}"/>
							</Grid>
						</DataTemplate>
					</Setter.Value>
				</Setter>
			</Style>
		</views:NodeView.TrailingControlPresenterStyle>
	</views:NodeView>
</UserControl>`

**Comment by Wouterdek** [comment]
Make sure your node views have matching node viewmodels attached to them, otherwise the logic that controls them won't work. [(API ref)](https://wouterdek.github.io/NodeNetwork/api/api/NodeNetwork.Views.NodeView.html#NodeNetwork_Views_NodeView_ViewModel)
