### ISSUE TITLE
Detecting nodes drag.

### ISSUE THREAD

**Issue by collectioner** [Wouterdek/NodeNetwork#56]
Hi,

Is there any way to detect the stop of nodes dragging/moving?

Thanks.

**Comment by collectioner** [comment]
Well, I found a workaround: add an observable for Position property. However, you'll get updates after each movement for each pixel. If it's not required, we can add Throttle with necessary time. I did it, but if there is better way - feel free to propose.

**Comment by Wouterdek** [comment]
I added node movement events to NetworkView in commit de29f54
