### ISSUE TITLE
Creating connections via code

### ISSUE THREAD

**Issue by jterry35** [Wouterdek/NodeNetwork#64]
Is there a way to create connections via code?

**Comment by Sage-of-Mirrors** [comment]
Yes. [Here is an example of how I do it in my application.](https://github.com/LordNed/Winditor/blob/event-mode/Editor/Editor/Modes/EventMode/EventMode.cs#L264)

**Comment by Wouterdek** [comment]
Jup.
In short, here is the relevant snippet:

```
var con = network.ConnectionFactory(input, output);
network.Connections.Edit(x => x.Add(con));
```
