### ISSUE TITLE
How to add grid on background of network view?

### ISSUE THREAD

**Issue by EagerTechnologies** [Wouterdek/NodeNetwork#67]
**Hello,**

Is there anyway I could possibly add a grid/guidelines similar to the Unreal Engine 4 Blueprint Graph on to the background of the network view? I would also like the grid/guidelines to move infinitely when dragging or is there not yet any way to do this?

**Thanks!**

**Comment by Wouterdek** [comment]
The same thing was asked in issue #61. The short answer is: I've added support for this in the code (commit 8d00fd0) and modified an example app to illustrate this, but no version with this code has been released yet.

**Comment by EagerTechnologies** [comment]
> The same thing was asked in issue #61. The short answer is: I've added support for this in the code (commit [8d00fd0](https://github.com/Wouterdek/NodeNetwork/commit/8d00fd0917eb0c0522f295f3af435087ef94ae7c)) and modified an example app to illustrate this, but no version with this code has been released yet.

Okay, thank you!

**Comment by EagerTechnologies** [comment]
> The same thing was asked in issue #61. The short answer is: I've added support for this in the code (commit [8d00fd0](https://github.com/Wouterdek/NodeNetwork/commit/8d00fd0917eb0c0522f295f3af435087ef94ae7c)) and modified an example app to illustrate this, but no version with this code has been released yet.

May I ask though, in that commit, you made some changes to some of the NodeNetwork xaml files, how can I access them?

**Comment by Wouterdek** [comment]
I'm not sure what you mean? The xaml edits are a one-time change to allow setting backgrounds on networkviews. The way to use it is shown in [ExampleCodeGenApp/Views/MainWindow.xaml](https://github.com/Wouterdek/NodeNetwork/blob/8d00fd0917eb0c0522f295f3af435087ef94ae7c/ExampleCodeGenApp/Views/MainWindow.xaml#L30)

**Comment by ChrisMGeo** [comment]
For me I had to use `NetworkView.Background` instead (I hope this is correct). Is it possible for the background image to move and zoom in with the rest of the network view, because when I do so it stays static?
