### ISSUE TITLE
Delete nodes

### ISSUE THREAD

**Issue by MMJM** [Wouterdek/NodeNetwork#7]
Hi,

This looks like a great project. I've started having a look at it and was wondering how to delete Nodes?

Thanks

**Comment by Wouterdek** [comment]
If you mean in the user interface, select them with the left mouse button and press delete.
If you mean in code, simply remove them from the Nodes list in the network.

**Comment by MMJM** [comment]
Thanks for the reply. It does indeed work. I must have tried that on the nodes that can't be deleted like the Output node in the calculator example.
