### ISSUE TITLE
Observe Nodes collections

### ISSUE THREAD

**Issue by jbltx** [Wouterdek/NodeNetwork#70]
Sorry for disturbing, I am not familiar with **ReactiveUI** concepts and I was wondering how I can observe changes in the `NetworkViewModel.Nodes` and `NetworkViewModel.SelectedNodes` ? 

I have a `Node` class and I store all `Node `instances in an `ObservableCollection `(which is handy to use with WPF bindings). I have created a custom `NodeViewModel `which contains a reference to a `Node `instance. So my workflow should be to observe the `NetworkViewModel `collections in order to update my own `ObservableCollection `behind it.

Based on what I read [there](https://github.com/reactiveui/DynamicData), I have tried this at MainWindow initialization, but both delegates **OnNodeChanged** and **OnNodeSelectionChanged** are never called : 

```cs
NodeNetwork = new NetworkViewModel();
NodeNetwork.Nodes.Connect().ForEachItemChange(OnNodeChanged);
NodeNetwork.SelectedNodes.Connect().QueryWhenChanged(OnNodeSelectionChanged);
```

Thank you !

**Comment by Wouterdek** [comment]
You might be missing `.Subscribe()` behind your calls.

**Comment by jbltx** [comment]
Ah yes, thank you for the quick answer !
