### ISSUE TITLE
NetworkChanged not firing when endpoints change

### ISSUE THREAD

**Issue by FabianNitsche** [Wouterdek/NodeNetwork#79]
The observable `NetworkViewModel.NetworkChanged` does not fire if Endpoints are added or removed. Is that the expected behavior?

If not, I can provide a PR. 

If yes I can handle this outside, no problem.

**Comment by Wouterdek** [comment]
Hmmm, the general intent behind that observable is to push changes that change the meaning/"value" of the network. I guess it makes sense to include changes in inputs/outputs. Changed in c9a7344.
