### ISSUE TITLE
Property to control Zoom In/Out the Network View.

### ISSUE THREAD

**Issue by sabapathygithub** [Wouterdek/NodeNetwork#81]
Hi,

First of all. Big thanks for this great library.

I have scenario here where we need provide an option to zoom in/out the Network View using button instead of mouse. Is there any property available to control it? 

Thanks

**Comment by sabapathygithub** [comment]
@Wouterdek : Thanks for adding this request as enhancement. 

Is there any suggestion or workaround to achieve this functionality with current version?

Thanks

**Comment by Wouterdek** [comment]
Zoom is controlled by the DragCanvas in NetworkView, which currently doesn't support setting zoom levels programmatically.

I'll be working on the library at the end of this month or the beginning of september, I'll look into it then.

**Comment by sabapathygithub** [comment]
@Wouterdek : Great. Many thanks for your prompt reply.

**Comment by Wouterdek** [comment]
Next version will have a `ZoomFactor` property on the NetworkViewModel.

**Comment by sabapathygithub** [comment]
@Wouterdek : Thank you.
