### ISSUE TITLE
Great Library - some questions

### ISSUE THREAD

**Issue by Shibulski** [Wouterdek/NodeNetwork#85]
Is it possible (out of the box) to have the endpoints on top/bottom instead left/right?
Is it possible (out of the box) to set the cardinality of the endpoints?

**Comment by Wouterdek** [comment]
> Is it possible (out of the box) to have the endpoints on top/bottom instead left/right?

No

> Is it possible (out of the box) to set the cardinality of the endpoints?

Cardinality as in number of connections at an endpoint? Yes, `Endpoint` has a `MaxConnections` property.

**Comment by Shibulski** [comment]
Thanks for your answer! How complicated would it be to enable the top/bottom endpoints feature? Just a matter of "tweaking" the xamls?

**Comment by Wouterdek** [comment]
> Thanks for your answer! How complicated would it be to enable the top/bottom endpoints feature? Just a matter of "tweaking" the xamls?

I think so, yes. The nodes, inputs and outputs can be customized heavily by changing out the `Template` they use. You can probably make a copy of the default template for [nodes](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Themes/NodeView.xaml) and [endpoints](https://github.com/Wouterdek/NodeNetwork/blob/master/NodeNetwork/Themes/Endpoint.xaml) and modify them to fit your usecase.
