### ISSUE TITLE
doesnt work under prism app

### ISSUE THREAD

**Issue by alexgubanow** [Wouterdek/NodeNetwork#87]
robust controls build using modern reactive MVVM code....
are u kidding? it doesnt work under prismlibrary project, reactiveui is yesterday, c'mon
view is view, viewmodel is viewmodel, why do u mess things up, viewmodel in view code behaind and so, whats that?

**Comment by Wouterdek** [comment]
Prism is not supported.

**Comment by alexgubanow** [comment]
please, WRITE THIS INFO ON MAIN PAGE. have spent time before understood, that ur control are useless

**Comment by FabianNitsche** [comment]
@alexgubanow Please communicate without insulting other developers and feel free to create and maintain your own node network gui library.
